[package]
name = "rusty-bits-embedded-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
defmt = "0.3.8"
defmt-rtt = "0.4.1"
panic-halt = "0.2.0"
rtt-target = "0.5.0"
